version: '2'
services:
  mongo:
    image: mongo:3.2
    # restart: always 
  redis:
    image: redis:3.2
    # restart: always
  api:
    build: .
    depends_on:
      - mongo
      - redis
    links:
      - mongo
      - redis
    ports: 
      - 9000:9000
    volumes:
      - .:/code
    environment:
      MONGO_URI: mongodb://mongo:27017
      REDIS_SOCKETIO_HOST: redis
    # restart: always
